version: '3'
services:
  MaJaJaserver:
    image: "wayne900619/majajalist"
    depends_on:
      - database
    volumes:
      - ./dist:/home/MaJaJalist/dist
    ports:
      - "80:80"
      - "443:443"
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MaJaJalist
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
