name: BuildTest
on: [pull_request]
jobs:
  BuildTest:
    name: tryToBuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Caching dependency
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: GoBuild
        run: go build -v .