name: DeployToServer
on:
  push:
    branches: [master]
jobs:
  Deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ['1.13.x']

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Caching dependency
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: GoTest
        run: |
          make test -v .

      - name: Build binary file
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o release/linux/amd64/helloworld

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: wayne900619/MaJaJalist
          username: wayne900619
          password: ${{ secrets.docker_password }}
          dockerfile: docker/Dockerfile

      - name: Deploy to my server
        uses: appleboy/ssh-action@v0.0.6
        with:
          host: ${{ secrets.ssh_host }}
          username: server
          password: ${{ secrets.ssh_password }}
          script_stop: true
          script: |
            wget https://raw.githubusercontent.com/txya900619/testGithubActions/master/start.sh -O MaJaJalistDeploy.sh
            sudo bash ./MaJaJalistDeploy.sh
            exit