name: ReviewDogLintAndBuildTest
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  golangci-lintAndCodecov:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint:latest
        # uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
        with:
          github_token: ${{ secrets.github_token }}
      - name: Build Codecov File
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}